### ISSUE TITLE
EC2 describeInstances return failure 

### ISSUE THREAD

**Issue by hodovani** [swift-aws/aws-sdk-appleos-core#1]
I used AWSSDK AppleOS 0.3.0 and  AWSSDK AppleOS Core 0.2.1 on macOS.

In the response to the EC2.describeInstances request I found error:

```swift
failure (
    Swift.DecodingError.dataCorrupted (
        Swift.DecodingError.Context (
            codingPath : [
                CodingKeys (stringValue: "reservationSet", intValue: nil),
                CodingKeys (stringValue: "instancesSet", intValue: nil),
                CodingKeys (stringValue: "platform", intValue: nil)
            ],
            debugDescription : "Cannot initialize PlatformValues from invalid String value windows",
            underlyingError : nil
        )
    )
)
```

The code that fire the issue:
```
    let ec2 = EC2(
        accessKeyId: accessKeyId,
        secretAccessKey: secretAccessKey,
        region: .euwest2
    )
    let instanceRequest = EC2.DescribeInstancesRequest()
    do {
      try ec2.describeInstances(instanceRequest).whenComplete { response in
        do {
            print(response)
        }
      }
    } catch {
      print(error)
    }
```

I got success result when I made same request in the terminal:
`aws ec2 describe-instances`

It might be problem with region, because if I change region to  `.useast1` in swift or in terminal it works correct and return successful result.

Can you please help me?

**Comment by adam-fowler** [comment]
This looks like a service model file out of date. I’m away at the moment so cannot verify. 

If you could stick a breakpoint in AWSClient.validate() and get the response body. If you could include that below in a comment without giving away too much about your setup that’d be great. 

I’ll have a look when I get back in the next few days

**Comment by hodovani** [comment]
I created gist with xml. [link](https://gist.github.com/hodovani/82b98a5b9c9b3ba5f811f00577508423)

Can you please have a look at it when you will have time. I replaced some part of ids, keys with stars(*).

Thanks 🙏

**Comment by adam-fowler** [comment]
Hi, is that the response data that is failing?  It seems to be from useast1, plus it doesn’t seem to contain a “platform” tag. Reading this on my phone so maybe I’ve missed it.

**Comment by hodovani** [comment]
@adam-fowler, Sorry 😞 wrong xml.
The correct [link](https://gist.github.com/hodovani/82b98a5b9c9b3ba5f811f00577508423) to the failure and correct response xml.

**Comment by MaxDesiatov** [comment]
@adam-fowler The error is caused by `PlatformValues` decoder being case sensitive. Or if we can assume that AWS always returns lowercase `windows` string, it could be fixed with lowercasing the raw value of the only case in `PlatformValues`.

**Comment by adam-fowler** [comment]
Thanks @MaxDesiatov. We can patch this within the CodeGenerator. I can add an entry for this enum. I’m gonna assume this is an error in the model file for the moment.

**Comment by MaxDesiatov** [comment]
@adam-fowler awesome, thanks. Will this need to be patched in both NIO 1.x and 2.x versions? Do these separate repositories correspond to these two NIO version by the way?

**Comment by adam-fowler** [comment]
@MaxDesiatov The original repository is a general purpose swift version. It works for macOS and server side swift. It currently is using NIO 1.4 as one of the main ways to use it server side is via Vapor, which doesn’t have a NIO2.0 release yet. We are looking to do a NIO2.0 of aws-ask-swift in the near future. A branch already exists that uses nio2.0. 

This repository uses the nio transport services which means it only works on apple os but allows it to work on iOS which aws-sdk-swift does not. As there are no requirements for this repository to be limited to nio1.4 I have already upgraded it to nio2.0.

**Comment by MaxDesiatov** [comment]
@adam-fowler great, thanks for the clarification. I was trying to understand these differences when debugging the issue, but wasn't able to find any relevant documentation on this. Maybe this detailed explanation from your comment could be added to README in the future. Sorry for the off topic.

**Comment by adam-fowler** [comment]
@hodovani Can you try the HEAD of aws-sdk-appleos to see if the latest has fixed your issue

**Comment by hodovani** [comment]
@adam-fowler thanks, the latest aws-sdk-appleos works great.
